name: Python CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install linting dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff

      - name: Run linter (Ruff)
        run: ruff check .

  test:
    name: Run Tests
    needs: lint
    runs-on: ubuntu-latest
    environment: main_env

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write .env
        shell: bash
        run: |
          {
          echo "APP_NAME=${{secrets.APP_NAME}}"
          echo "DATABASE_URL=${{secrets.DATABASE_URL}}"
          echo "API_KEY=${{secrets.API_KEY}}"
          echo "API_KEY_NAME=${{secrets.API_KEY_NAME}}"
          echo "REDIS_HOST=${{secrets.REDIS_HOST}}"
          echo "REDIS_PORT=${{secrets.REDIS_PORT}}"
          echo "SECRET_KEY=${{secrets.SECRET_KEY}}"
          echo "ALGORITHM=${{secrets.ALGORITHM}}"
          echo "ACCESS_TOKEN_EXPIRE_MINUTES=${{secrets.ACCESS_TOKEN_EXPIRE_MINUTES}}"
          echo "REFRESH_TOKEN_EXPIRE_MINUTES=${{secrets.REFRESH_TOKEN_EXPIRE_MINUTES}}"
          echo "MAX_API_KEY_LIFETIME_SECONDS=${{secrets.MAX_API_KEY_LIFETIME_SECONDS}}"
          } >> .env

          # fallback dacă variabilele sunt goale
          sed -i '/^REDIS_PORT=$/d' .env && echo "REDIS_PORT=6379" >> .env
          sed -i '/^ACCESS_TOKEN_EXPIRE_MINUTES=$/d' .env && echo "ACCESS_TOKEN_EXPIRE_MINUTES=15" >> .env
          sed -i '/^REFRESH_TOKEN_EXPIRE_MINUTES=$/d' .env && echo "REFRESH_TOKEN_EXPIRE_MINUTES=60" >> .env
          sed -i '/^MAX_API_KEY_LIFETIME_SECONDS=$/d' .env && echo "MAX_API_KEY_LIFETIME_SECONDS=86400" >> .env

          echo "DATABASE_URL=${{secrets.DATABASE_URL}}"
          
          cat .env
      - name: Run tests with pytest
        run: pytest
